"""Independent exact reconstruction of the L2 phase-5 averaged composition.

The verifier does not import the constructor.  It rebuilds each block kernel,
reconstructs the occupancy convolution, checks the hypergeometric orbit-average
identity, checks the factorial Vandermonde identity and every row in the claimed
band, and checks the complete odd-q centralizer generated by pair permutations
and endpoint swaps.
"""
from __future__ import annotations

import argparse
import itertools
import json
import math
from fractions import Fraction
from pathlib import Path


def comps(total, parts):
    if parts == 1:
        yield (total,)
    else:
        for first in range(total + 1):
            for tail in comps(total - first, parts - 1):
                yield (first,) + tail


def ff(n, d):
    return math.prod(n - j for j in range(d))


def sigma_data(q, target):
    sigma = tuple((target - a) % q for a in range(q))
    fixed = [a for a in range(q) if sigma[a] == a]
    assert q % 2 == 1 and len(fixed) == 1
    used = set(fixed)
    pairs = []
    for a in range(q):
        if a not in used:
            b = sigma[a]
            pairs.append(tuple(sorted((a, b))))
            used.update((a, b))
    return sigma, fixed[0], tuple(sorted(pairs))


def total_rows(block_size, r):
    low, extra = divmod(block_size, r)
    assert low >= 2
    row = (low + 1,) * extra + (low,) * (r - extra)
    return tuple(sorted(set(itertools.permutations(row))))


def axis(s):
    return (((s, 0), Fraction(1, 2)), ((0, s), Fraction(1, 2)))


def interior(s):
    a, b = s // 2, s - s // 2
    return (((a, b), Fraction(1)),) if a == b else (
        ((a, b), Fraction(1, 2)), ((b, a), Fraction(1, 2))
    )


def outer(r):
    nodes = [0]
    k = 1
    while k <= r:
        nodes.append(k)
        k *= 5
    raw = {x: Fraction(1, math.prod(x - y for y in nodes if y != x)) for x in nodes}
    if raw[0] > 0:
        raw = {x: -w for x, w in raw.items()}
    norm = sum(abs(w) for w in raw.values())
    return {x: w / norm for x, w in raw.items()}


def block_measure(block_size, q, target):
    sigma, fixed, pairs = sigma_data(q, target)
    rows = total_rows(block_size, len(pairs))
    layers = outer(len(pairs))
    answer = {}
    for row in rows:
        for k, layer_weight in layers.items():
            for active_tuple in itertools.combinations(range(len(pairs)), k):
                active = set(active_tuple)
                base = Fraction(1, len(rows)) * layer_weight / math.comb(len(pairs), k)
                tables = [interior(s) if j in active else axis(s) for j, s in enumerate(row)]
                for choices in itertools.product(*tables):
                    counts = [0] * q
                    weight = base
                    for (a, b), ((i, j), local_weight) in zip(pairs, choices):
                        counts[a], counts[b] = i, j
                        weight *= local_weight
                    key = tuple(counts)
                    answer[key] = answer.get(key, Fraction(0)) + weight
    return sigma, fixed, pairs, layers, {x: w for x, w in answer.items() if w}


def convolve(a, b):
    answer = {}
    for x, wx in a.items():
        for y, wy in b.items():
            z = tuple(i + j for i, j in zip(x, y))
            answer[z] = answer.get(z, Fraction(0)) + wx * wy
    return {x: w for x, w in answer.items() if w}


def label(counts, sigma):
    return 1 if any(
        (a == b and counts[a] >= 2) or (a != b and counts[a] and counts[b])
        for a, b in enumerate(sigma)
    ) else -1


def multinomial(counts):
    answer = math.factorial(sum(counts))
    for count in counts:
        answer //= math.factorial(count)
    return answer


def centralizer_maps(q, fixed, pairs):
    maps = []
    for pair_permutation in itertools.permutations(range(len(pairs))):
        for swaps in itertools.product((0, 1), repeat=len(pairs)):
            permutation = [None] * q
            permutation[fixed] = fixed
            for source_index, target_index in enumerate(pair_permutation):
                source = pairs[source_index]
                target = pairs[target_index]
                if swaps[source_index]:
                    target = (target[1], target[0])
                permutation[source[0]], permutation[source[1]] = target
            maps.append(tuple(permutation))
    assert len(set(maps)) == (2 ** len(pairs)) * math.factorial(len(pairs))
    return tuple(maps)


def moved(counts, permutation):
    answer = [0] * len(counts)
    for old, new in enumerate(permutation):
        answer[new] = counts[old]
    return tuple(answer)


def parse_weights(record):
    return {
        tuple(item["counts"]): Fraction(item["weight"])
        for item in record["normalized_weights"]
    }


def moment(measure, alpha):
    return sum(
        weight * math.prod(ff(counts[a], alpha[a]) for a in range(len(alpha)))
        for counts, weight in measure.items()
    )


def verify(record):
    n, q, target, block_count = record["case"]
    assert block_count == 2
    block_size = n // block_count
    sigma, fixed, pairs, layers, block = block_measure(block_size, q, target)
    raw_average = convolve(block, block)
    raw_no = sum(w for x, w in raw_average.items() if label(x, sigma) == -1)
    orientation = -1 if raw_no > 0 else 1
    oriented = {x: orientation * w for x, w in raw_average.items()}
    norm = sum(abs(w) for w in oriented.values())
    normalized = {x: w / norm for x, w in oriented.items()}
    assert normalized == parse_weights(record)
    assert norm == Fraction(record["post_average_l1_before_renormalization"])
    assert sum(abs(w) for w in normalized.values()) == 1
    correlation = sum(w * label(x, sigma) for x, w in normalized.items())
    assert correlation == Fraction(record["normalized_true_2sum_correlation"])

    # Orbit average = hypergeometric mixture over block occupancy splits.
    hypergeometric_cells = 0
    for total_counts, convolution_weight in raw_average.items():
        orbit = multinomial(total_counts)
        averaged_density = convolution_weight / orbit
        reconstructed_density = Fraction(0)
        for x, wx in block.items():
            y = tuple(total_counts[a] - x[a] for a in range(q))
            if min(y) < 0 or y not in block:
                continue
            hypergeometric = Fraction(multinomial(x) * multinomial(y), orbit)
            reconstructed_density += (
                hypergeometric * wx / multinomial(x) * block[y] / multinomial(y)
            )
            hypergeometric_cells += 1
        assert reconstructed_density == averaged_density

    # The convolution factorial moment is the two-block Vandermonde split.
    rows = 0
    vandermonde_splits = 0
    band = record["averaged_band"]
    for degree in range(band):
        for alpha in comps(degree, q):
            rows += 1
            raw_global_moment = moment(raw_average, alpha)
            reconstructed = Fraction(0)
            ranges = [range(value + 1) for value in alpha]
            for beta in itertools.product(*ranges):
                gamma = tuple(alpha[a] - beta[a] for a in range(q))
                coefficient = math.prod(math.comb(alpha[a], beta[a]) for a in range(q))
                reconstructed += coefficient * moment(block, beta) * moment(block, gamma)
                vandermonde_splits += 1
            assert reconstructed == raw_global_moment == 0
    assert rows == record["factorial_rows_checked"]

    group = centralizer_maps(q, fixed, pairs)
    for counts, weight in normalized.items():
        for permutation in group:
            assert normalized.get(moved(counts, permutation), Fraction(0)) == weight

    r = len(pairs)
    expected_cross_factor = Fraction(1, 2 ** r)
    expected_no = abs(layers[0]) ** 2 * expected_cross_factor
    assert -sum(w for x, w in oriented.items() if label(x, sigma) == -1) == expected_no
    assert expected_cross_factor == Fraction(record["cross_block_no_consistency_factor"])
    layer_masses = {}
    layer_signs = {}
    for counts, weight in normalized.items():
        layer = sum(bool(counts[a] and counts[b]) for a, b in pairs)
        layer_masses[layer] = layer_masses.get(layer, Fraction(0)) + weight
        layer_signs.setdefault(layer, set()).add(1 if weight > 0 else -1)
    assert {str(k): str(v) for k, v in sorted(layer_masses.items())} == record[
        "global_K_layer_signed_masses"
    ]
    assert [k for k, signs in sorted(layer_signs.items()) if len(signs) == 2] == record[
        "global_K_layers_with_both_weight_signs"
    ]
    # Every five-condition M2 mixture has a common nonzero product sign on
    # every global K layer.  Either signature below is representation-independent.
    assert any(len(signs) == 2 for signs in layer_signs.values())
    return {
        "case": record["case"],
        "formula_reconstruction": "PASS",
        "hypergeometric_split_cells": hypergeometric_cells,
        "vandermonde_splits": vandermonde_splits,
        "factorial_rows": rows,
        "centralizer_order": len(group),
        "post_average_l1": str(norm),
        "normalized_correlation": str(correlation),
        "strictly_above_two_thirds": correlation > Fraction(2, 3),
        "m2_condition_5_escape_signature": "PASS",
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", required=True, type=Path)
    args = parser.parse_args()
    payload = json.loads(args.input.read_text(encoding="utf-8"))
    checks = [verify(record) for record in payload["records"]]
    print(json.dumps({
        "arithmetic": "fractions.Fraction",
        "imports_constructor": False,
        "checks": checks,
        "verification": "PASS",
    }, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
